Lartu/ldpl

src/ldpl.cpp
I was having issues with using `\n` and friends, and I think it's because the tokenizer wasn't passing something along. 
Sorry about the coding style, you can test this using this program:
```
$ cat escape.ldpl
PROCEDURE:
display "\t\e[33mi\e[32mn \e[31mt\e[34me\e[35mc\e[36mh\e[37mn\e[1m\e[31mi\e[32mc\e[33mo\e[34ml\e[35mo\e[36mu\e[37mr\e[0m\r\n" 
```
On master:
```
$ ldpl escape.ldpl
LDPL Error: unknown escape sequence on a VECTOR access.
```
Should work better in a modern terminal with this patch.
=> include the \ in escape codes

src/makefile
On macOS 10.14.1:
```
$ make
awk -f lib-to-string.awk ldpl_lib.cpp > ldpl_included_lib.cpp
c++ -g -c -Wall -std=gnu++11 -fpermissive -DVERSION='"2.0.7"'   -DSTANDARD=19         -DCOMPILEDATE='"Tue Mar 12 22:23:30 PDT 2019"' ldpl.cpp
c++ -g ldpl.o -o ldpl -static-libgcc -static-libstdc++ 
clang: error: unsupported option '-static-libgcc'
make: *** [all] Error 1
```
clang has a `-static` option, but using it fails with `ld: library not found for -lcrt0.o`. 
[From developer.apple.com](https://developer.apple.com/library/archive/qa/qa1118/_index.html#//apple_ref/doc/uid/DTS10001666). 
> Apple does not support statically linked binaries on Mac OS X. A statically linked binary assumes binary compatibility at the kernel system call interface, and we do not make any guarantees on that front. …
=> clang doesn't really support -static on darwin

src/ldpl_included_lib.cpp, src/ldpl_lib.cpp
This script errors on master with `ldpl-temp.cpp:218:6: error: no viable overloaded operator[] for type
'ldpl_str_vector'` but works with this PR:
```COBOL
DATA:
v is text vector
z is number vector
PROCEDURE:
store "Bart" in v:"name"
display v:"name" crlf
store 123 in z:"header"
store 987 in z:"footer"
display z:"footer"
```
Adding operator overloads fixes it for me but I'm not sure if there is a better way to go from literals to strings in C++.
=> Add operator for v:"key"

src/ldpl_included_lib.cpp, src/ldpl_lib.cpp
This is a fix for the bug introduced in #20. It looks like the compiler was casting ints to ldpl_numbers before, but with the char* arg introduced it couldn't do the implicit cast anymore. So adding an int arg operator fixes it and catches all three cases of a string literal, whole number, and ldpl_number. But I don't know if other casting issues will arise here.
=> Fix the broken vector keys fix

src/ldpl.cpp, src/ldpl.h
Sorry for all the spam today :)  While poking around vector index, I found what I think is a bug. The strings are being uppercased by the tokenizer, eg `list:"bob"` is becoming `LIST:"BOB"`. So you can't have both list:"bob" and list:"BOB", but you can still do list:x where x is "bob" to access a lowercase version. The standard says `myVector:"hello" #Stores 1 in the subindex "hello" of myVector` so I think the bug is in the tokenizer doing the uppercasing, so that's what I changed.
Here's a program to demonstrate:
```cobol
DATA:
v is text vector
z is number vector
x is text
PROCEDURE:
store "i" in x
store 1 in v:"i"
store 2 in v:"I"
display v:x crlf
display v:"i" crlf
display v:"I" crlf
```
Should see "1 1 2", not "2 2".
=> Fix for literal string index

src/ldpl_lib.cpp
I think the `to_string()` was producing something different for ints and the number type, so casting them all to the same type fixed the quine for me.
However I couldn't get any warnings on Linux even when the quine was broken so I'm not sure if this will fix the issue you mentioned in #22. What compiler are you using? I have `gcc (GCC) 8.2.1 20190131`.
=> Enforce all numbers to use the same type

src/ldpl.cpp, src/ldpl_lib.cpp
LDPL does not care about the order of the elements in a map so we can use unordered_map which is much faster for the average case. There were also many unnecessary overloads since most of them can be implicitly converted.
=> Change VECTOR C++ implementation to unordered_map and simplify it

src/ldpl.cpp
Tiny :bug: I ran into, the `while $string not equal to $string` statements are using `==` in the c++ code. 
Script to test:
```cobol
DATA:
string is text 
char is text
i is number
PROCEDURE:
store "~imagination~" in string
store 0 in i
get character at i from string in char
while char is not equal to "" do
display i ":char: " char crlf
add 1 and i in i
get character at i from string in char
repeat
display i crlf
=> Make != match the 'not equal' in while statement

src/ldpl.cpp, src/ldpl.h
Previously a command such as:
```
ldpl -h foo
```
or
```
ldpl -v foo
```
would ignore the help/version argument and attempt to run the file foo.
This commit changes this behavior such that any time -v, --version, -h,
or --help is supplied the version/help info will be displayed.
----
Example
```
~/code/ldpl/src[master !?]$ ./ldpl-master -h
Usage: ldpl [options] file [arguments]
Options:
-h --help                Display this information
-r                       Display generated C++ code
-i=<file>                Include file in current compilation
-v --version             Display LDPL version information
~/code/ldpl/src[master !?]$ ./ldpl-master --help
Usage: ldpl [options] file [arguments]
Options:
-h --help                Display this information
-r                       Display …
```
=> -v, --version, -h, or --help take priority

README.md, src/ldpl.cpp
Note that it needs an `=`, just like the `-i` flag. 
**Example:**
```
$ ldpl ../examples/99bottles.ldpl
LDPL: Compiling...
* File(s) compiled successfully.
* Saved as ldpl-output-bin
$ ldpl -o=99b ../examples/99bottles.ldpl
LDPL: Compiling...
* File(s) compiled successfully.
* Saved as 99b
$ ./99b
99 bottles of beer on the wall,
99 bottles of beer.
Take one down, pass it around,
98 bottles of beer on the wall...
```
**Updated -h:**
```
$ ldpl -h                                                                             ☰ ~/Code/ldpl/ldpl/src:o-flag
Usage: ldpl [options] file [arguments]
Options:
-h --help                Display this information
-r                       Display generated C++ code
-o=<name>                Set output file for compiled binary
-i=<file>                Include …
```
=> Add -o option to compiler that allows naming the output binary

src/ldpl.cpp, src/ldpl.h, src/ldpl_lib.cpp
Possible solution for #33 
Using this code:
```cobol
DATA:
t is text
PROCEDURE:
store 3.14 in t
display t crlf
store 100 in t
display t crlf
store 88.0123456789 in t
display t crlf
```
Output before this patch:
```
3.140000
100
88.012346
```
After this patch:
```
3.14
100
88.0123456789
```
I looked into overriding the default `std::to_string(double)` but it apparently can't be done, and also the precision can't be changed from 6, but maybe there's another cleaner way?
=> Kill trailing 0s when converting from number->text

src/ldpl.cpp
Tested it on Arch Linux and Ubuntu, should only trigger for Linux systems. Possible solution for #38
=> Produce static binaries on Linux

src/ldpl.cpp, src/ldpl.h
My boss is really getting on my case about the big rewrite of our cryptocurrency platform in LDPL. He says we're not going to be able to move fast and break things if we don't have `GOTO` in the language.
I told him most people think `GOTO` is more harmful than helpful, and that it's known to be especially dangerous in complicated systems, but he said that he looked up this Dijkstra guy and he wasn't impressed with his Github profile.
So anyway, this patch adds two new keywords to LDPL: `GOTO` and `LABEL`. They are just piggybacking C++'s `goto`, really. Pretty barebones.
They have to both be used together in the same sub-procedure or in the main code body of an LDPL program. So you can't `goto` across functions or anything like that. 
Here's a little example script to test:
```cobol …
```
=> Add GOTO & LABEL

src/ldpl.cpp
The way `fix_identifier` encodes invalid characters is causing some collisions, I think because it's only using the alphabet. 
For example, `-` and `_` both become `r_U`.
This patch changes it so the raw character number is used instead. The mangled names are nastier, but there won't be collisions.
The reason I didn't just "fix" this in master is I'm wondering if you had any other ideas for how to solve for the collisions? 
**Currently:**
```
one-two => VAR_ONEr_UTWO
one_two => VAR_ONEr_UTWO
one😎two => VAR_ONEr_Fr_Yr_Rr_HTWO
```
**With this patch:**
```
one-two => VAR_ONEc45_TWO
one_two => VAR_ONEc95_TWO
one😎two => VAR_ONEc4294967280_c4294967199_c4294967192_c4294967182_TWO
```
Here's a working example:
```
$ cat bug.lsc
DATA:
one-two is text
one_two is text
PROCEDURE:
store "okay" in …
```
=> Convert invalid chars to numbers, not letters

src/ldpl.cpp
=> Revert "Re-use IF code for ELSE IF"

src/ldpl.cpp, src/ldpl.h
This is a possible implementation for #12. Maybe people want to make HTML templates and stuff, well, now they can pretty easily using `STORE QUOTE IN $str-var` and `END QUOTE` syntax:
```
DATA:
content is text
PROCEDURE:
STORE QUOTE IN content
No strings attached! "This is a quote!" I said.
All the whitespace and whatnot comes, too.
\t\t Nothing is escaped. This \t is just \ and t. 
Everything but the final newline. You've gotta add that, if you want it. -> 
END QUOTE
display "Here's the quote: " crlf content crlf 
```
Output:
```
Here's the quote: 
No strings attached! "This is a quote!" I said.
All the whitespace and whatnot comes, too.
\t\t Nothing is escaped. This \t is just \ and t.
Everything but the final newline. You've gotta add that, if you want it. ->
```
Notes:
- Nothing is …
=> STORE QUOTE syntax for multi-line, literal strings

src/ldpl.cpp
The check was being done on "$name" instead of the token.
Example code:
```ldpl
DATA:
a:a is number
```
=> Check for ':' in names

src/ldpl.cpp
In the case of 'if', the if counter was incremented, so you could actually declare a variable before this PR if you close an extra if but the error would be found by the C++ compiler.
Example codes:
```ldpl
DATA:
if is number
PROCEDURE:
end if
```
```ldpl
DATA:
else is number
```
=> Allow declaration of variables named 'if' and 'else'

src/ldpl.cpp
The names of vector used in subindexes were not capitalized if the last index was a text literal.
Example code:
```ldpl
DATA:
v is number vector
PROCEDURE:
display v:v:"hi" crlf 
```
=> Capitalize all vector names in subindexes

src/ldpl.cpp, src/ldpl.h
Now we check proper closing of nested blocks, throwing error if we find something like this:
```ldpl
PROCEDURE:
sub-procedure mySubprocedure
if "" is equal to "" then
while "" is not equal to "" do
end sub-procedure
end if
repeat
```
We also check that there isn't an unterminated procedure block, like this:
```ldpl
PROCEDURE:
sub-procedure mySubprocedure
```
=> Improve block closing errors

src/ldpl.cpp, src/ldpl.h
I reduced the number of "ifs line_like" to only one per statement (except for variable declarations because I'm tired (? ), using more generic model lines like `IF $condition THEN`, `JOIN $expression AND $expression IN $str-var` and `ADD $num-expr AND $num-expr IN $num-var`.
I think this makes the code more readeable and maintainable, way less error-prone, and it makes it easier to add statements.
As far as I know I tested each statement (and its possibles argument combinations) and they work, and all the repo examples as well. But since is a pretty big PR I think it needs a review.
=> One if per statement

src/ldpl.cpp
The stod test passed on strings that starts like a number (`"1a"`, `"0.3e23udonki"`), producing errors on C++ compiling. Now the whole string must be a valid numeric representation.
Example:
```ldpl
PROCEDURE:
display 0.3e23udonki
```
=> Check whole string in is_number

src/ldpl.cpp, src/ldpl.h
This is basic support for expressions as per #41. 
The syntax is: `IN num-var SOLVE math-expression`
Right now it only supports the big four `+-*/` operations. It could be expanded to support `abs` and `ceil` probably, if that's the direction we want to go, but this was the simplest since it's just re-using C++'s operators. 
**Example**
```python
DATA:
square/num is number
square/res is number
x is number
y is number 
z is number
PROCEDURE:
sub-procedure square
in square/res solve square/num * square/num
end sub-procedure
store 10 in square/num
call square 
display "the square of " square/num " is " square/res crlf
store 1 in x
store 2 in y
in z solve x + y
display x " + " y " = " z crlf
in z solve x * (20 / (1 + y + y)) - 3.14
display "z: " z crlf 
```
**Output**
```
$ ./math-bin …
```
=> Add basic support for math expressions with IN-SOLVE

src/ldpl.cpp, src/ldpl.h
`is_vector_index` wan't working correctly, it allowed using anything except vector variables as the last index, so you could do something like this (the error would be found on the C++ compiling phase):
```ldpl
DATA:
v is number vector
PROCEDURE:
display v:coso
```
In the process of fixing it I made a lot of changes. I deleted `is_vector_index`, `split_vector` now returns two parts (the vector and the index) and `get_c_variable` is simpler.
=> The last vector index must be an expression

README.md
Earlier, I was trying to build LDPL on Windows (for æsthetic reasons, let's say) and stumble on a lenghty compilation error. `ldpl_included_lib.cpp` was ill-formed.
I had no such issue on GNU/Linux, and I quickly found out that Awk does not work well with DOS EOL. For instance, where you would expect:
```cpp
void add_ldpllib(compiler_state & state){
state.add_var_code("#include <sstream>");
state.add_var_code("#include <math.h>");
```
this is what I had:
```cpp
void add_ldpllib(compiler_state & state){
state.add_var_code("#include <sstream>
");
state.add_var_code("#include <math.h>
");
```
I though it would be wise to mention in the README that windows user should change their git config to use Unix EOL. It's not like it's an issue with most available tools and editor nowadays.
I'll also …
=> Advise Windows user to change git core.autoclrf config

src/ldpl.cpp
Files passed to `-i=` on the command line are being compiled in the reverse order given, leading to (unexpected?) dependency issues.
For example:
```
$ cat a.ldpl 
DATA:
a is text
$ cat b.ldpl 
DATA:
b is text
PROCEDURE:
store "yay" in a
$ cat c.ldpl  
PROCEDURE:
display a crlf
display b crlf
$ ldpl -i=a.ldpl -i=b.ldpl c.ldpl 
LDPL Error: Malformed statement (b.ldpl:5)
```
This errors because `b.ldpl` is actually compiled first right now. With this patch, running the same code above preserves the compilation order:
```
$ ldpl -i=a.ldpl -i=b.ldpl c.ldpl 
LDPL: Compiling...
* File(s) compiled successfully.
* Saved as c-bin
$ ./c-bin
yay
```
I know we're going to rework `-i` in the future but I thought this might be worth changing now.
=> Make -i include order match what's passed

src/ldpl.cpp
These might be redundant because you can just do `add 1 and var in var`, but I tend to do that a lot so thought this might be worth exploring. Tests are in Lartu/ldpltest#4. 
Example:
```
DATA:
n is number
PROCEDURE:
while n is less than 100 do
display "n: " n crlf
incr n
repeat
display "final: " n crlf
```
Wasn't sure about `INCR` vs `INCREMENT` too?
=> INCR & DECR statements

src/ldpl.cpp, src/ldpl.h, src/ldpl_lib.cpp
This is much nicer than #93. This patch implements the `SPLIT` statement that was already listed as a `TODO` in the source. It lets you easily just split a string or file into a vector and loop over that, and avoids all the caching nonsense.
```
DATA:
words is text vector
PROCEDURE:
SPLIT "hi there" BY " " IN words
DISPLAY words:1 crlf
```
output:
```
there
```
If you want to get all the characters, you can split by `""`:
```
SPLIT "hi there" BY "" IN letters
DISPLAY letters:1 crlf
```
output:
```
i
```
And of course, the whole point - it works with utf8:
```
split "🐈 say meow, 🐕 say woof" by "" in letters
display letters:0 crlf
display letters:6 letters:7 letters:8 letters:9 crlf
display letters:12 crlf
```
output:
```
🐈
meow
🐕
```
=> SPLIT text statement

src/ldpl.cpp, src/ldpl_lib.cpp
This adds the REPLACE statement, which as an unimplemented TODO in the source:
```
REPLACE $str-expr FROM $str-expr WITH $str-expr IN $str-var
```
example:
```
DATA:
string IS text
PROCEDURE:
STORE "Please reject this Pull Request." IN string
REPLACE "reject" FROM string WITH "accept" IN string
DISPLAY string crlf
REPLACE "Pull Request" FROM string WITH "lizard" IN string
REPLACE "accept" FROM string WITH "admire" IN string
REPLACE "." FROM string WITH ": 🦎" IN string
DISPLAY string crlf
```
output:
```
Please accept this Pull Request.
Please admire this lizard: 🦎
```
=> REPLACE statement

src/ldpl.cpp, src/ldpl_lib.cpp
Continuing the conversation from 3f5325a613435b9ac478a9bfc4b002537d5e5084...
Currently on `master,` the exit code for `EXECUTE - AND STORE EXIT CODE IN` is always 0. I did some digging and it looks like BSD has a different WEXITSTATUS() macro than Linux:
> OpenBSD's implementation of WEXITSTATUS uses the address-of operator (unary &) on its argument, effectively requiring that its argument have storage. You are calling it with the return value of a function, which doesn't have storage, so the compiler complains. - https://stackoverflow.com/a/13674801
Here's BSD/Mac's: 
https://github.com/apple/darwin-xnu/blob/0a798f6738bc1db01281fc08ae024145e84df927/bsd/sys/wait.h#L144
Which uses the `_W_INT` macro:
https://github.com/apple/darwin-xnu/blob/0a798f6738bc1db01281fc08ae024145e84df927/bsd/sys/w …
=> Fix exit code on BSD/Mac

src/ldpl.cpp
in order to delete the temporary cpp file (`ldpl-temp.cpp`) the compiler called the `rm` system command.
windows does not have this command, and instead has `del`.
I added a simple preprocessor check that will use `del` on windows and `rm` on everything else.
=> temporary cpp file is now deleted correctly on windows

src/ldpl.cpp, src/ldpl.h
This resolves #113. Currently only `LOCAL DATA` section is implemented for now, I'll implement `PARAMETERS` later, you can review and test the code in the meantime.
Example:
```
DATA:
x is number
PROCEDURE:
sub-procedure foo
LOCAL DATA:
i is number
PROCEDURE:
incr i
display "FOO " i crlf
end sub-procedure
sub-procedure bar
LOCAL DATA:
i is text
PROCEDURE:
join i and "-" in i
display "BAR " i crlf
end sub-procedure
for x from 0 to 10 step 1 do
call foo
call bar
repeat
```
Output:
```
FOO 1
BAR -
FOO 2
BAR --
FOO 3
BAR ---
FOO 4
BAR ----
FOO 5
BAR -----
FOO 6
BAR ------
FOO 7
BAR -------
FOO 8
BAR --------
FOO 9
BAR ---------
FOO 10
BAR ----------
```
All the variable declaration statements where merged to only one if to reduce duplicated code.
We store in which subprocedure a variable was …
=> PARAMETERS, LOCAL DATA & CREATE STATEMENT

src/ldpl.cpp, src/ldpl.h
As per the discussion on lartu/ldpl-ncurses#2, this adds support for an OS-specific version of the `FLAG` statement:
````coffeescript
extension "ldpl-ncurses.cpp"
flag "-O3"
flag linux "-lncursesw"
flag macos "-lncurses"
flag macos "-D_XOPEN_SOURCE_EXTENDED"
````
This will always pass `"-O3"` to the compiler (the same as how `FLAG` works today), but it will check the LDPL compiler's OS to determine whether to pass the additional flags.
The new statement uses the standard C/C++ macros listed at https://sourceforge.net/p/predef/wiki/OperatingSystems/ to detect which OS the user is running. These should be very resilient as they are what "regular" C and C++ programs use to do OS detection. As such, we will probably not need to change the current list but may need to add new entries as new …
=> Add OS-specific `FLAG` statement

src/ldpl.cpp
Just an idea I had, since the backwards nesting of multicontainer type names is a bit confusing to me.
What if instead of this:
````coffeescript
DATA:
groceries IS number list
names IS text map
````
you could do this:
````coffeescript
DATA:
groceries IS list of numbers
names IS map of text
````
And instead of this:
````coffeescript
DATA:
myVariable is text list list
myOtherVariable is number map list map map list map
pleaseStop is text list list map list list map map map list map map list
````
You could, but should never, do this:
````coffeescript
DATA:
myVariable is list of list of text
myOtherVariable is map of list of map of map of list of map of number
pleaseStop is list of map of map of list of map of map of map of list of list of map of list of list of text
````
This branch adds …
=> Experimental new nested type syntax.

src/ldpl.cpp
This adds support for using the plural version of type names in multicontainers.
For example, `list of maps of numbers` or `map of maps of lists of maps of text`.
The regular, non-plural type names are still supported, and the first container must always be singular (so you can't do `lists of text`, but you can do `list of lists of text`).
=> Support plural multicontainer type names

docs/data.md
This switches the docs to use `list of map of text` and such instead of `text map list`. The 4.3 syntax still works so I have a note saying as much.
=> Switch to `X of Y` syntax in docs

src/lib-to-string.sh
This allows the build to work on OpenBSD.
=> Convert #!/bin/bash to #!/usr/bin/env bash for consistency.

docs/index.md
=> spelling mistake in documentation index.md

src/ldpl.cpp, src/ldpl.h
This patch adds hacky debug information for the sourcecode, a demo can be seen [here](https://asciinema.org/a/sZsT6BY4QLhGMe1QXZTT9kNj6). The patch **should** support interaction with cpp extensions (but i haven't tested that).
For more information on what does this patch do you can read the documentation on the `#line` preprocessor directive:
* [cppreference](https://en.cppreference.com/w/cpp/preprocessor/line)
* [microsoft documentation](https://docs.microsoft.com/en-us/cpp/preprocessor/hash-line-directive-c-cpp)
* [gcc documentation](https://gcc.gnu.org/onlinedocs/cpp/Line-Control.html)
=> Hacky debuginfo for sourcecode

examples/cpp-extension/hello.cpp
This should fix the problem with the "Hello" C++ example extension raised in #176.
=> Update C++ example to newer API

src/ldpl.cpp
Very short filenames result in the following crash:
(gdb) frame 8
108	                if(0 == arg.compare(arg.length()-5, 5, ".ldpl")||0 == arg.compare(arg.length()-4, 4, ".lsc")){
With this patch, the shortest accepted filenames are ".ldpl" and ".lsc".
For shorter names we will get a cryptic error now:
LDPL Error: filename expected.
=> ldpl -o=t -i=x should not crash

src/ldpl.cpp
Instead of:
LDPL Error: filename expected.
exit with:
LDPL Error: no source files specified. Note: source file names have to end with ".ldpl" or ".lsc"
=> Improve error message when no source files are specified.

src/ldpl.cpp
Compiler complains that this line is not there and refuses to compile ldpl if it isn't
=> Make LDPL compile again

docs/text.md, src/aux/aux_compile_line.cpp, src/ldpl_lib/ldpl_lib.cpp
This is something else I uncovered while trying to convert compileman.php to LDPL: no uppercase/lowercase conversion in LDPL by default. I think it's handy to have these included in the language.
```coffeescript
DATA:
input is text
output is text
PROCEDURE:
store "ldpl updates? great!" in input
convert input to uppercase in output
display "input: " input crlf
display "output: " output crlf
```
```
$ ./example-bin
input: ldpl updates? great!
output: LDPL UPDATES? GREAT!
```
=> Added `CONVERT _ TO UPPERCASE/LOWERCASE IN _` statements
