Lartu/ldpl

- src/ldpl.cpp
- src/nvm.h
Command to transform a character code into a character (STORE CHARACTER CODE OF str IN num)
Command to read all the lines in stdin (ACCEPT str-var UNTIL EOF)
> Added two new commands

- src/cpptrim.h
- src/ldpl.cpp
- src/ldpl.h
- src/ldpl_lib.cpp
- src/makefile
The .h and .cpp files contained a mix of tab and space indentation.
These, in addition to the makefile, also contained end-of-line
whitespace.
This commit adjusts this whitespace so that it is consistent across all
source files.
> Whitespace adjustments

- src/ldpl.cpp
Instead of duplicating all the `IF` statements for `ELSE IF`, what do you think about checking for `ELSE IF` early and then just prepending `}else` to all the regular compiled `if(...){` C++ code? That's what I've done in this patch, hopefully it makes sense. 
The goal was to prevent simple mistakes in the future - if someone comes in and modifies `IF x IS GREATER THAN x` for some reason, they might forget to also modify `ELSE IF x IS GREATER THAN x`.
> Re-use IF code for ELSE IF

- src/ldpl.cpp
- src/ldpl.h
Should fix #47 on both Mac and Linux this time. 
I also simplified (I think) the `if_stack` code by just using a counter and only incrementing it on `IF` - not on `ELSE IF`.
> Try to compact `else if` again

- src/ldpl.cpp
See discussion at https://github.com/Lartu/ldpl/pull/64#issuecomment-485819198
> Prohibit sub-procedure declaration inside if and while blocks

- src/ldpl.cpp
- src/ldpl.h
Now we check for things like this:
```ldpl
PROCEDURE:
if 0 is equal to 0 then
display 0
else
display 1
else
display 2
else if 0 is equal to 0 then
display 3
end if
```
>  No ELSE or ELSE IF after ELSE

- src/ldpl.cpp
- src/ldpl.h
> Revert "Revert "The last vector index must be an expression""

- src/ldpl.cpp
- src/ldpl.h
This adds a FOR statement, following this syntax:
```ldpl
FOR i FROM x TO y STEP z DO
#FOR body
NEXT
```
where `i` is a number variable and `x`, `y` and `z` are number variables or literals.
First, it assigns `x` to `i` and starts an iteration. At the start of an iteration, the condition `i <= y` is evaluated if `x < y` and `i >= y` otherwise. If the condition passes, the `FOR` body is executed, if it fails the loop ends. After the body is executed, `i` is incremented by `z` and a new iteration is started (checking the condition and so on).
The `BREAK` and `CONTINUE` statements can be using inside `FOR` loops.
I used `NEXT` to mark the end of a `FOR` loop, but it could be `REPEAT` like in the `WHILE` loop without any trouble, if you prefer it.
Examples:
```ldpl
DATA:
i is number …
```
> FOR statement

- src/ldpl.cpp
- src/ldpl.h
This resolves #120 .
Examples:
```ldpl
DATA:
letter IS TEXT
letters IS TEXT LIST
PROCEDURE:
PUSH "L" TO letters
PUSH "D" TO letters
PUSH "P" TO letters
PUSH "L" TO letters
FOR EACH letter IN letters DO
DISPLAY letter
REPEAT
```
```ldpl
DATA:
number IS NUMBER
numbers IS NUMBER MAP
PROCEDURE:
STORE 1 IN numbers:"One"
STORE 2 IN numbers:"Two"
STORE 3 IN numbers:"Three"
FOR EACH number IN numbers DO
DISPLAY number
REPEAT
```
> FOR EACH statement

- src/ldpl.cpp
added an import statement of the following form:
`IMPORT <string>`
you can only import before any other segment is declared.
> Import statement

- src/ldpl.cpp
- src/ldpl.h
This PR allows more complex conditions in `IF`and `WHILE` statements, using `AND`, `OR` and parenthesis. So, valid conditions are:
* `condition1 AND condition2`, `condition1` and `condition2` being valid conditions
* `condition1 OR condition2`, `condition1` and `condition2` being valid conditions
* `( condition )`, `condition` being valid a conditions
* any valid LDPL condition before this PR
Like C++, the usual precedence rules and short-circuit evaluation are applied.
Example:
```
...
if length is greater than 0 and ( names:0 is equal to "Alice" or names:0 is equal to "Bob" ) then
...
end if
```
> Compound conditions

- examples/strcmp-demo.ldpl
- src/ldpl.cpp
- src/ldpl_lib.cpp
Add the ability to compare strings, as suggested in issue #125 
Also add a simple demonstration of this string-comparison in examples/strcmp-demo.ldpl
> Add string comparison

- docs/structure.md
Added basic docs for #156 to the docs markdown.
> Document per-os `flag` option.

- docs/io.md
> Add docs for new APPEND and WRITE error codes

- README.md
- man/ldpl.1
- man/ldplman-intro
- src/ldpl.cpp
I'm retiring my old github username and switching to a new one for the new year. 
- the artist formerly known as *dvkt*
> I changed my github username

- src/ldpl_lib.cpp
Use C strings with size for construction.
> Load files via mmap.

- Dockerfile
Agregué un archivo llamado Dockerfile que permite construir con docker un container que compila ldpl. Montando un volumen con los archivos puede usarse para compilar y probar los programas.
> Add Dockerfile with Alpine

- docs/cppext.md
> Spelling and Grammar fixes

- docs/data.md
> Grammar fixes

- CONTRIBUTING.md
also changed the D in Dinosaur Tamers to be a capital letter, because the Dinosaurs deserve it
> Grammar update

- docs/list.md
- src/aux/aux_compile_line.cpp
> Added `REMOVE ELEMENT AT _ FROM _` statement`

- README.md
> LDPL 5 Release Candidate
